data:
  build: database
  entrypoint: echo
db:
  build: database
  ports:
    - "5984"
  volumes_from:
    - data
app:
  build: .
  links:
    - db:couchdb
  ports:
    - "3000"
  environment:
    - COUCHDB_ADMIN_NAME
    - COUCHDB_ADMIN_PASS
    - COUCHDB_PUBLIC_URL
    - COUCHDB_PUBLIC_PORT
